name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - Gestion_de_stock_Backend_APS

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}